### ISSUE TITLE
Linuxkit install no longer working

### ISSUE THREAD

**Issue by stijnopheide** [vouch-opensource/linuxkit-image-development#2]
Installing linuxkit from source is no longer working. This has to be fixed by using the binary install.

Maybe adding a parameter to the terraform module with the URL to the github artifact is a nice way to control linuxkit versions? This way we can use official releases of linuxkit by default, but point to another artifact in case you want to have a newer version.

**Comment by raphapr** [comment]
https://github.com/vouch-opensource/linuxkit-image-development/pull/3 fix it. In review.
